export const courses = [
  {
    id: "dsa",
    title: "Data Structures and Algorithms",
    code: "CS101",
    degree: "BSc Computer Science",
    subject: "Computer science",
    modules: ["Arrays", "Linked Lists", "Stacks", "Queues", "Trees", "Graphs"],
  },
  {
    id: "os",
    title: "Operating Systems",
    code: "CS102",
    degree: "BSc Computer Science",
    subject: "Computer science",
    modules: [
      "Processes",
      "Threads",
      "Scheduling",
      "Deadlocks",
      "Memory Management",
      "File Systems",
    ],
  },
  {
    id: "math1",
    title: "Linear Algebra",
    code: "MA101",
    degree: "BSc Mathematics",
    subject: "Mathematics",
    modules: [
      "Matrices",
      "Vectors",
      "Eigenvalues",
      "Determinants",
      "Linear Transformations",
      "Rank",
    ],
  },
  {
    id: "phy1",
    title: "Classical Mechanics",
    code: "PH101",
    degree: "BSc Physics",
    subject: "Physics",
    modules: [
      "Motion",
      "Forces",
      "Energy",
      "Momentum",
      "Work",
      "Rotational Motion",
    ],
  },
  {
    id: "bio1",
    title: "Cell Biology",
    code: "BI101",
    degree: "BSc Biology",
    subject: "Biology",
    modules: [
      "Cell Structure",
      "DNA",
      "Proteins",
      "Cell Division",
      "Enzymes",
      "Metabolism",
    ],
  },
  {
    id: "chem1",
    title: "Organic Chemistry",
    code: "CH101",
    degree: "BSc Chemistry",
    subject: "Chemistry",
    modules: [
      "Hydrocarbons",
      "Alcohols",
      "Aldehydes",
      "Ketones",
      "Acids",
      "Reactions",
    ],
  },
];
